### ISSUE TITLE
Plugin: Refactor=>Extract=>Variable drops last character

### ISSUE THREAD

**Issue by rkitts** [gosu-lang/gosu-lang#11]
Take this code:

retVal = ProductType.valueOf(components[components.length - 2])

highlight the argument to valueOf (i.e. components[components.length - 2])

Right click, Refactor=>Extract=>Variable. Type in a variable name, say x. This is the result:

  var x = components[components.length - 2

Notice the dropped closing bracket.

**Comment by DPUkyle** [comment]
Closing; Guidewire controls the IDE plugin.
