### ISSUE TITLE
Gosu code for Fetch top 10 records for H2 Database

### ISSUE THREAD

**Issue by Selvakumargosu** [gosu-lang/gosu-lang#117]
Dear All,
Now I am facing one issue. Kindly suggest me.
Currently we are fetching all records as "query.select()". But I want to fetch only frist 10 records. Kindly guide me

var query = gw.api.database.Query.make(Message)
query.compare("DestinationID", Equals, 24)
var results = query.select()
var count = results.Count
var startRow = count < limit ? 0 : count - limit
var iter = results.iterator(startRow)
while (iter.hasNext()){
                 var message = iter.next()
  gw.transaction.Transaction.runWithNewBundle(\bundle -> {
   bundle.add(message)     }, "su")
  message.skip()
}

Regards
Selvakumar.M
+91 8056246746

**Comment by abhijay94** [comment]
Hi @Selvakumargosu 

There is an easy way to chunk query results. You can use com.google.common.collect.Iterables.limit to chunk the result size.

`var query = gw.api.database.Query.make(Message)
query.compare("DestinationID", Equals, 24)
var queryResult = query.select()
var chunkSize = 10
queryResult.setPageSize(chunkSize)
var limitedResult = com.google.common.collect.Iterables.limit(queryResult , chunkSize)
limitedResult.each(\ c -> print(c))`

Hope this helps.
Thanks

**Comment by DPUkyle** [comment]
Sorry, we can't provide support for proprietary Guidewire classes such as `gw.transaction.Transaction` here.
