### ISSUE TITLE
Not able to click on file/Edit options etc. in Intellija IDEA on studio 1.1.10

### ISSUE THREAD

**Issue by varghesekrenny** [gosu-lang/gosu-lang#118]
Hi 
I am using Guidewire studio 1.1.10 and version 903 and while launching the studio in windows 7, it is some times showing the black screen or not able to click on menu options. There is no error scene on the log.  I am using jdk1.8.0_144. Please address this problem.

**Comment by vicky17d** [comment]
Please log Guidewire specific issues on Jira
Use Java 1.8.0_92. That might solve the problem.
