### ISSUE TITLE
Possible locale issue with gw.specContrib.expressions.binding.ScienceMiscTest ?

### ISSUE THREAD

**Issue by DPUkyle** [gosu-lang/gosu-lang#122]
PR #121 referenced a failure with `ScienceMiscTest`. I suspect this might be related to locale or OS-specific issues relating to binding expression interpretation.

@przemelek can you please share the stack trace or failure logs from this test on your local machine? 

This test [passes](https://circleci.com/gh/gosu-lang/gosu-lang/2275) in our CI environment ([junit XML](https://2275-21134995-gh.circle-artifacts.com/0/tmp/circle-junit.cuzEr4t/junit/TEST-gw.specContrib.expressions.binding.ScienceMiscTest.xml))

**Comment by przemelek** [comment]
Strange thing I was sure that this was failing both on my macOS, and on my Ubuntu, but as I can say on macOS it passes without problems, but fails on Ubuntu.
Results :

Failed tests: 
  ScienceMiscTest>TestClass.run:151->TestClass.reallyRun:155->TestClass.runBare:160->TestClass.reallyRunBare:165->TestClass.runTest:220->TestClass.doRunTest:263->testMisc:20 expected same:<Newton Meter> was not:<Joule>

Stack trace isn't too helpful:
-------------------------------------------------------------------------------
Test set: gw.specContrib.expressions.binding.ScienceMiscTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE! - in gw.specContrib.expressions.binding.ScienceMiscTest
testMisc(gw.specContrib.expressions.binding.ScienceMiscTest)  Time elapsed: 0.007 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected same:<Newton Meter> was not:<Joule>
	at gw.specContrib.expressions.binding.ScienceMiscTest.testMisc(ScienceMiscTest.gs:20)

**Comment by DPUkyle** [comment]
OK, is there a JUnit xml file you can share? Perhaps under
`gosu-test/target/surefire-reports/TEST-gw.specContrib.expressions.binding.ScienceMiscTest.xml`?

**Comment by DPUkyle** [comment]
Thanks @przemelek; is there a JUnit xml file you can share? Perhaps under `gosu-test/target/surefire-reports/TEST-gw.specContrib.expressions.binding.ScienceMiscTest.xml`?

**Comment by przemelek** [comment]
`<testsuite xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="gw.specContrib.expressions.binding.ScienceMiscTest" time="0.008" tests="2" errors="0" skipped="0" failures="1"><properties><property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/><property name="java.protocol.handler.pkgs" value="gw.internal.gosu.compiler.protocols"/><property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/><property name="java.vm.version" value="25.151-b12"/><property name="java.vm.vendor" value="Oracle Corporation"/><property name="maven.multiModuleProjectDirectory" value="/home/przemelek/space/gosu-lang"/><property name="java.vendor.url" value="http://java.oracle.com/"/><property name="path.separator" value=":"/><property name="guice.disable.misplaced.annotation.check" value="true"/><property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/><property name="file.encoding.pkg" value="sun.io"/><property name="user.country" value="PL"/><property name="sun.java.launcher" value="SUN_STANDARD"/><property name="sun.os.patch.level" value="unknown"/><property name="java.vm.specification.name" value="Java Virtual Machine Specification"/><property name="user.dir" value="/home/przemelek/space/gosu-lang/gosu-core-api-precompiled"/><property name="java.runtime.version" value="1.8.0_151-b12"/><property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/><property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/><property name="os.arch" value="amd64"/><property name="java.io.tmpdir" value="/tmp"/><property name="line.separator" value="
"/><property name="java.vm.specification.vendor" value="Oracle Corporation"/><property name="os.name" value="Linux"/><property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/><property name="sun.jnu.encoding" value="UTF-8"/><property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/><property name="java.specification.name" value="Java Platform API Specification"/><property name="java.class.version" value="52.0"/><property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/><property name="os.version" value="4.4.0-104-generic"/><property name="user.home" value="/home/przemelek"/><property name="user.timezone" value="Europe/Warsaw"/><property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/><property name="java.specification.version" value="1.8"/><property name="file.encoding" value="UTF-8"/><property name="user.name" value="przemelek"/><property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/><property name="java.vm.specification.version" value="1.8"/><property name="sun.arch.data.model" value="64"/><property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/><property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -e test"/><property name="java.specification.vendor" value="Oracle Corporation"/><property name="user.language" value="pl"/><property name="awt.toolkit" value="sun.awt.X11.XToolkit"/><property name="java.vm.info" value="mixed mode"/><property name="java.version" value="1.8.0_151"/><property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/><property name="securerandom.source" value="file:/dev/./urandom"/><property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/><property name="java.vendor" value="Oracle Corporation"/><property name="maven.home" value="/usr/share/maven"/><property name="file.separator" value="/"/><property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/><property name="sun.cpu.endian" value="little"/><property name="sun.io.unicode.encoding" value="UnicodeLittle"/><property name="sun.desktop" value="gnome"/><property name="sun.cpu.isalist" value=""/></properties><testcase name="testMisc" classname="gw.specContrib.expressions.binding.ScienceMiscTest" time="0.007"><failure message="expected same:<Newton Meter> was not:<Joule>" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected same:<Newton Meter> was not:<Joule>
	at gw.specContrib.expressions.binding.ScienceMiscTest.testMisc(ScienceMiscTest.gs:20)
</failure></testcase><testcase name="testLengthUnits" classname="gw.specContrib.expressions.binding.ScienceMiscTest" time="0.001"/></testsuite>`

**Comment by DPUkyle** [comment]
Strange. I thought it might be somehow related to `user.language=pl`, so I ran locally with `$ mvn clean test -Duser.language=pl` but it passes for me. Hmm.

**Comment by DPUkyle** [comment]
We finally figured out the cause of the non-determinism in `ScienceMiscTest` -  a cache was being evicted by `ScienceUnitConversionTest`. When that test runs prior to `ScienceMiscTest`, bad things happen.

This is fixed (for now) in 082c51e3ed0e2e05989f9a3498e1fc53938bccc7. Closing.
