### ISSUE TITLE
Reverse type inference regression in 1.14.x

### ISSUE THREAD

**Issue by DPUkyle** [gosu-lang/gosu-lang#126]
The below example passed in 1.13.x, fails in 1.14.x:
```
function hello<T>(t : T) : T{ return null }
  
function foo1() {
    var bar: ArrayList<Integer> = hello(new ArrayList( ))  // Reverse type inference: new ArrayList() ==> new ArrayList<Integer>() from context for the type param T
  }
```
See FIXME tags in `gosu-test/src/test/gosu/gw/specContrib/typeinference/GenericResultToParameter.gs` and `gosu-test/src/test/gosu/gw/specContrib/typeinference/Errant_DiamondInference.gs`

This maps to Guidewire IDE-4166

**Comment by rsmckinney** [comment]
That particular inference is no longer supported
