### ISSUE TITLE
java.lang.NoClassDefFoundError: gw/lang/enhancements/CoreFileEnhancement

### ISSUE THREAD

**Issue by sayewich** [gosu-lang/gosu-lang#143]
I am trying to use spring boot to wrap the gosu required jar files into a self-executing jar file.

It has been working splendidly until I tried to use the OOTB GOSU enhancement "eachFileInTree" from the Core FileEnhancement.gsx Enhancement.

Please advise

I get the following exception.

(note the two issues:
   *  !! Unable to dynamically compile Java from source.  tools.jar is missing from classpath.
   *   java.lang.ClassNotFoundException: gw.lang.enhancements.CoreFileEnhancement
)

!! Unable to dynamically compile Java from source.  tools.jar is missing from classpath.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.NoClassDefFoundError: gw/lang/enhancements/CoreFileEnhancement
        at play.FileList.main(FileList.gs:14)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: gw.lang.enhancements.CoreFileEnhancement
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 9 more

Here is my code
package play

uses org.slf4j.LoggerFactory

uses java.io.File

class FileList {
  static var _logger = LoggerFactory.getLogger(FileList.Class)
  static public function main(args : String[]) {
    _logger.debug("==========> {}", "Start")

    var sourcePath = "D:/wa/pc/modules/configuration/gsrc/"
    var aFile = new File(sourcePath)
    aFile.eachFileInTree(\file -> {
      if (file.isFile()) {
      //var tmp = new FileModel(file)
        _logger.debug("==> {} <==", file.Path)
      } else {
        _logger.debug("'{}' is not a file skipping", file.Name)
      }
    })

    _logger.debug("<========== {}", "End")
  }
}

and the pom file

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>helloworld</groupId>
    <artifactId>heloworld</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <gosu.version>1.14.10</gosu.version>
        <spring.boot.version>2.0.1.RELEASE</spring.boot.version>
        <poi.version>3.17</poi.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.1.RELEASE</version>
    </parent>

    <dependencies>

        <dependency>
            <groupId>org.gosu-lang.gosu</groupId>
            <artifactId>gosu-core-api</artifactId>
            <version>${gosu.version}</version>
        </dependency>

        <dependency>
            <groupId>org.gosu-lang.gosu</groupId>
            <artifactId>gosu-core</artifactId>
            <version>${gosu.version}</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.gosu-lang.gosu</groupId>
            <artifactId>gosu-maven-compiler</artifactId>
            <version>${gosu.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>helloworld</finalName>

        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                        <configuration>
                            <classifier>spring-boot</classifier>
                            <mainClass>
                                play.FileList
                            </mainClass>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.9.1</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/gosu</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/test/gosu</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <executions>
                    <execution>
                        <id>Compile Gosu sources</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <compilerId>gosuc</compilerId>
                        </configuration>
                    </execution>
                    <execution>
                        <id>Compile Gosu test sources</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <compilerId>gosuc</compilerId>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.gosu-lang.gosu</groupId>
                        <artifactId>gosu-maven-compiler</artifactId>
                        <version>${gosu.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

        </plugins>
    </build>

</project>

Kyle Moore thought that I need to tweak the über-jar’s manifest to include the Contains-Sources attribute.

I added the following lines to the <plugins> of  <build> section

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <archive>
            <manifestEntries>
                <Contains-Sources>gs,gsx</Contains-Sources>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>

With no luck

Kyle observed that spring-boot doesn't flatten the dependencies like the shade plugin does. Instead the dependencies are relocated to BOOT-INF/lib/. Gosu probably needs a code change to accommodate this use case.

Hence the creation of this issue.

**Comment by DPUkyle** [comment]
Thanks @sayewich for logging this.

I've created a sample repo at [DPUkyle/spring-boot-gosu](https://github.com/DPUkyle/spring-boot-gosu) to illustrate the problem, and I'm thinking about where/how we can make Gosu play nice with spring-boot.

**Comment by DPUkyle** [comment]
This is fixed via some spring-boot-maven-plugin configuration. Please see DPUkyle/spring-boot-gosu@109ea42eb7ad98cfc6237b80a3431ee09b3533c2 for the solution.
