### ISSUE TITLE
Add logical XOR operation

### ISSUE THREAD

**Issue by tredontho** [gosu-lang/gosu-lang#145]
Is there a practical reason for not including a logical xor (that operates on boolean types)?  It seems like the `^` operator is only valid for ints and longs, which diverges from Java functionality where it's overloaded for both integer types and boolean types.  

I had one of those rare cases where it would have been useful and was just curious why it might be missing.

Thanks!

**Comment by rsmckinney** [comment]
xor supports boolean operands in gosu 1.13.x
