### ISSUE TITLE
Compile fails on JDK 17

### ISSUE THREAD

**Issue by josimar-silva** [gosu-lang/gosu-lang#179]
Overview
-----------
Is it planned, in the foreseeable future, for Gosu to support JDK 17? 

I've tried compiling a simple Gosu [project](https://github.com/FRI-DAY/sonar-gosu-plugin/tree/main/src/testIntegration/resources/projects/simple-gosu-project) with JDK 17 and got the following error:
![compile-gosu-java-17](https://user-images.githubusercontent.com/4359233/232099979-8d3820d2-ad4c-473d-8232-27048f29991f.png)

_Environment_
- JDK: OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
- OS: Linux 64
- Gosu Core API: 1.15.8

**Comment by sadheeshv** [comment]
Could you try using the following snapshot of Gosu (Java 17/11 supported) which is still under development https://oss.sonatype.org/content/repositories/snapshots/org/gosu-lang/gosu/gosu/1.17.0-SNAPSHOT/

**Comment by josimar-silva** [comment]
> Could you try using the following snapshot of Gosu (Java 17/11 supported) which is still under development https://oss.sonatype.org/content/repositories/snapshots/org/gosu-lang/gosu/gosu/1.17.0-SNAPSHOT/

Thanks @sadheeshv. The project compiled successfully with the snapshot version.
