### ISSUE TITLE
Can't build gosu-lang

### ISSUE THREAD

**Issue by rkitts** [gosu-lang/gosu-lang#20]
git clone https://github.com/gosu-lang/gosu-lang.git
   <cloning messages>
cd gosu-lang
mvn process-classes
  <maven messages>
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.673s
[INFO] Finished at: Thu Sep 04 07:37:28 PDT 2014
[INFO] Final Memory: 107M/777M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gosu-test-api: Compilation failure: Compilation failure:
[ERROR] /Users/rkitts/work/gosu-lang/gosu-test-api/src/main/java/gw/testharness/KnownBreakConditionPredicate.java:[11,20] error: package org.fest.util does not exist
[ERROR] /Users/rkitts/work/gosu-lang/gosu-test-api/src/main/java/gw/testharness/KnownBreakConditionPredicate.java:[38,15] error: cannot find symbol

--- environment stuff ---
[~/work/gosu-lang]: java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
[~/work/gosu-lang]: mvn -version
Apache Maven 3.0.4 (r1232337; 2012-01-17 00:44:56-0800)
Maven home: /Users/rkitts/work/gwire/rickkittssmbpro/maven/apache-maven-3.0.4
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.4", arch: "x86_64", family: "mac"
[~/work/gosu-lang]:

**Comment by lboasso** [comment]
fixed
