### ISSUE TITLE
Move idea-gosu-plugin, ij-compiler-api and ij-editor-devtools into the specific Maven profile 

### ISSUE THREAD

**Issue by vbauer** [gosu-lang/gosu-lang#39]
Could you please add possibility to build most part of Gosu modules without necessity to clone Intellij IDEA's sources? It could be separate Maven module with (or without) activation condition on env.IDEA_HOME.

I understand that it's possible to:
* comment unnecessary modules
* use newest Maven and "-pl" parameter

... but it's not so comfortable as out-of-box optional profile.

**Comment by lboasso** [comment]
I moved those modules in a profile.
Now(v1.4) you can build Gosu only with mvn compile.

**Comment by vbauer** [comment]
Thanks!
