### ISSUE TITLE
Unable to mock with Mockito or EasyMock

### ISSUE THREAD

**Issue by VJGosu** [gosu-lang/gosu-lang#44]
When trying to mock with mockito framework getting a runtime exception from Gosu.

java.lang.IllegalStateException: Could not find method for when on org.mockito.Mockito with specified param types

  at gw.internal.gosu.runtime.GosuRuntimeMethods.invokeMethodInfo(GosuRuntimeMethods.java:111)

  at program_.__Program__1556$TestMockito.testMock(Unknown Source)

The program is as below.
------------------------
uses org.mockito.Mockito

class TestMockito 
{
  
  function testMock()
  {
      var orig : Original = new Original()
      print("*************************** In the mock test sampler")
      var shar1 =  Mockito.mock(Original)
      var result = Mockito.when(shar1.testMe()).thenReturn("MockTested")
      print(result)
  }
}

class Original
{
  function testMe() : String
  {  
    return "tested"
  }
}

var t : TestMockito = new TestMockito()
t.testMock()

**Comment by DPUkyle** [comment]
This appears to be working with no trouble; maybe in your case there was a dependency resolution problem when executing from the Gosu Scratchpad.

I built a variation on your example here:
https://github.com/DPUkyle/example-gosu-mockito

Please check it out!
