### ISSUE TITLE
Elvis operator evaluates first operand twice in case it passes null check

### ISSUE THREAD

**Issue by Useful-Idiot** [gosu-lang/gosu-lang#59]
Don't really know if it is a bug or intended behavior, but here's the code sample:

    var counter = 0
    var incr : block() : String = \ -> {
        counter += 1
        return "a"
    }

    var t = incr() ?: "b"

    print(t)
    print(counter)

yields 

    "a"
    2

It makes sense if you think about elvis operator as shorthand syntax for x != null ? x  : y, but it can be misleading when you skim over the code.

If it is a bug I could try fixing it.

**Comment by lboasso** [comment]
It's a bug :)
You are welcome to fix it and issue a pull request

**Comment by Useful-Idiot** [comment]
Commit history shows it has been fixed several hours after I opened this issue, but changes were reverted afterwards. What's current status?

**Comment by lboasso** [comment]
It's currently fixed in our spec branch, but we decided not to release the fix yet as we need more time to test it
