### ISSUE TITLE
support override modifier in property short syntax

### ISSUE THREAD

**Issue by kevur** [gosu-lang/gosu-lang#67]
Hi,

It is perfectly fine and possible to override property set and property get "functions" and annotate them properly:

```
var _someProperty = 0
override property get SomeProperty(): int {
  return this._someProperty
}
override property set SomeProperty(value: int) {
  this._someProperty = value
}
```

However, it is impossible to use the short syntax and make it easily visible that this overrides some method from the parent class / interface. We can see this in the [grammar on the gosu homepage](http://gosu-lang.github.io/grammar.html).

```
var _someProperty: int as SomeProperty = 0 // we cannot put an "override" here
```

The same goes with readonly properties:

```
final var _someProeprty: int as readonly SomeProperty = 0 // we cannot put an "override" here
```

Are there plans to support something like that?

**Comment by lboasso** [comment]
You are right, there is currently no way to make it explicit that we are overriding some method.
Although the main purpose of the short syntax is indeed to be concise :)
We are not planing to add this functionality as you can be explicit with the classic override property get / set syntax
