### ISSUE TITLE
Error:Cannot find or create Gosu Compiler 

### ISSUE THREAD

**Issue by ReutChemo** [gosu-lang/gosu-lang#70]
hello! 
I'm installed IntelliJ 14.1.6 
                    SDK 1.8 (8.60)
                    and JARs jar idea-gosu-plugin-3.8.5
and still get this error..  (Error:Cannot find or create Gosu Compiler )
what can i do?

**Comment by lboasso** [comment]
Hello,

It seems you don't have Gosu's jars in the class path.
Have you followed the instructions(Step By Step) below:

http://gosu-lang.github.io/intellij.html

Or if you prefer maven or grade:
http://gosu-lang.github.io/docs.html

Cheers,
Luca

**Comment by ReutChemo** [comment]
hii
i actually do have the JARs :
[image: Inline image 1]
and still it's wrote :
Error:Cannot find or create Gosu Compiler
ᐧ

**Comment by lboasso** [comment]
I cannot see the image

**Comment by ReutChemo** [comment]
<img width="952" alt="default" src="https://cloud.githubusercontent.com/assets/17803374/13726289/9363664a-e8c9-11e5-97f9-4d5de30d9ded.PNG">

**Comment by lboasso** [comment]
Those are very old and incompatible jars.
Gosu latest jars can be found in our distribution here:
http://search.maven.org/remotecontent?filepath=org/gosu-lang/gosu/gosu/1.13/gosu-1.13-full.zip

Remove all those jars from your JDK and add the one from the gosu-1.13-full.zip file (inside the lib folder).
The proper place to add them would be in the Libraries section , not the SDK.
Please see this step by step gif:

http://gosu-lang.github.io/img/quickstart/4_create_project.gif

**Comment by lboasso** [comment]
I'll close the issue, let me know if you need more help setting up your environment.
You can ask questions here: https://groups.google.com/forum/#!forum/gosu-lang
