### ISSUE TITLE
Static imports fail with ambiguous type parameters

### ISSUE THREAD

**Issue by DPUkyle** [gosu-lang/gosu-lang#78]
On the gosu-lang email list, @hiraethus pointed out unexpected behavior using the new static import syntax.

@rsmckinney and I traced the problem down to `org.hamcrest.core.IsEqual#equalTo`. This is because the class defines a type parameter `<T>`, but the static method `equalTo` also defines a type parameter `<T>`. 

```
public class IsEqual<T> extends BaseMatcher<T> {
...
    public static <T> Matcher<T> equalTo(T operand) {
        return new IsEqual<T>(operand);
    }
```

Despite having the same name, these two parameters have no relationship - and in fact, creating such ambiguous class/method declarations is disallowed in Gosu. In other words, this could only happen when performing a static import from a Java type.

We are currently preparing a fix for the parser to address this.

**Comment by DPUkyle** [comment]
@rsmckinney fixed this with commits 24ca6e642fb1536278e308b15cc741b8e7bb6fdf and 8e7881c46da7e1a9b04dd0202ddcbb824f26c467.

Testing is still in progress.

**Comment by DPUkyle** [comment]
This is now fixed.

@hiraethus please compile your project again using version 1.14.1

**Comment by hiraethus** [comment]
Thanks very much!
